# Generated by Django 3.1.5 on 2021-01-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('jid', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=500)),
                ('destination', models.CharField(max_length=500)),
                ('port', models.IntegerField(max_length=50)),
                ('comment', models.CharField(max_length=500)),
                ('protocol', models.CharField(max_length=500)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
