# Generated by Django 3.1.5 on 2021-01-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='port',
            field=models.IntegerField(),
        ),
    ]
