# Generated by Django 3.1.5 on 2021-01-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='destination',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='rule',
            name='path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='rule',
            name='source',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='rule',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
